version: '3.7'

services:
  symfony:
    image: php:8.0-fpm
    container_name: symfony
    volumes:
      - ./your_project:/var/www/html
    networks:
      - app-network
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Interface Web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
